# Generated by Django 4.2.6 on 2024-01-05 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SchoolForm',
            new_name='School',
        ),
    ]
