# Generated by Django 4.2.6 on 2024-01-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_schoolform_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='Email',
            field=models.EmailField(default='rohit@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='school',
            name='ReenterEmail',
            field=models.EmailField(default='rohit@gamil.com', max_length=254),
        ),
    ]
