# Generated by Django 4.2.6 on 2024-01-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_school_email_school_reenteremail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='school',
            name='ReenterEmail',
        ),
        migrations.AddField(
            model_name='school',
            name='email',
            field=models.EmailField(default='sunil@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='school',
            name='reenteremail',
            field=models.EmailField(default='sunil@gmail.com', max_length=254),
        ),
    ]
